model_configs:
  - name: "hs1-encoder"
    model: "models/harmony-ai-solutions/harmonyspeech/encoder"
    model_type: "HarmonySpeechEncoder"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "hs1-synthesizer"
    model: "models/harmony-ai-solutions/harmonyspeech/synthesizer"
    model_type: "HarmonySpeechSynthesizer"
    max_batch_size: 10
    device_config:
      device: "cpu"

  - name: "hs1-vocoder"
    model: "models/harmony-ai-solutions/harmonyspeech/vocoder"
    model_type: "HarmonySpeechVocoder"
    max_batch_size: 10
    device_config:
      device: "cpu"

#    download_dir: "models/harmonyspeech/encoder"
#    load_format: "pt"
#    dtype: "float32"
#    seed: 42
#    enforce_eager: True

#  - model: "model2"
#    max_batch_size: 64
#    device_config:
#      device: "cpu"
#    download_dir: "models/"
#    load_format: "auto"
#    dtype: "float16"
#    seed: 123
#    enforce_eager: False