model_configs:
  - name: "hs1-encoder"
    model: "harmony-ai/harmony-speech-v1"
    model_type: "HarmonySpeechEncoder"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "hs1-synthesizer"
    model: "models/harmony-ai-solutions/harmonyspeech"
    model_type: "HarmonySpeechSynthesizer"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "hs1-vocoder"
    model: "models/harmony-ai-solutions/harmonyspeech"
    model_type: "HarmonySpeechVocoder"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov1-synthesizer-en"
    model: "models/myshell-ai/openvoice"
    model_type: "OpenVoiceV1Synthesizer"
    language: "EN"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov1-synthesizer-zh"
    model: "models/myshell-ai/openvoice"
    model_type: "OpenVoiceV1Synthesizer"
    language: "ZH"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov1-tone-converter"
    model: "models/myshell-ai/openvoice"
    model_type: "OpenVoiceV1ToneConverter"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov2-synthesizer-en"
    model: "models/myshell-ai/MeloTTS-English-v3"
    model_type: "MeloTTSSynthesizer"
    language: "EN"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov2-synthesizer-zh"
    model: "models/myshell-ai/MeloTTS-Chinese"
    model_type: "MeloTTSSynthesizer"
    language: "ZH"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"

  - name: "ov2-tone-converter"
    model: "models/myshell-ai/openvoice_v2"
    model_type: "OpenVoiceV2ToneConverter"
    max_batch_size: 10
    dtype: "float32"
    device_config:
      device: "cpu"
#
#  - name: "hs1-vocoder"
#    model: "models/harmony-ai-solutions/harmonyspeech/vocoder"
#    model_type: "HarmonySpeechVocoder"
#    max_batch_size: 10
#    dtype: "float32"
#    device_config:
#      device: "cpu"

#    download_dir: "models/harmonyspeech/encoder"
#    load_format: "pt"
#    dtype: "float32"
#    seed: 42
#    enforce_eager: True

#  - model: "model2"
#    max_batch_size: 64
#    device_config:
#      device: "cpu"
#    download_dir: "models/"
#    load_format: "auto"
#    dtype: "float16"
#    seed: 123
#    enforce_eager: False