services:
  harmonyspeech-ui:
#    build: ./frontend
    image: harmonyai/harmonyspeech-ui:latest
    pull_policy: always
    ports:
      - "8080:80"
    depends_on:
      - harmonyspeech-engine

  harmonyspeech-engine:
#    build: ./docker/nvidia
    image: harmonyai/harmonyspeech-engine-nvidia:latest
    pull_policy: always
    env_file: ./.env
    volumes:
      - ./config.gpu.yml:/app/harmony-speech-engine/config.yml
      - ./cache:/app/harmony-speech-engine/cache
    ports:
      - "12080:12080"
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [ gpu ]
